Repository UNLV-CS472-672/2024-F-GROUP1-Tabby, pull requests merged in 2024-11, with the labels that each got.

#39 Update issue templates
  .github/ISSUE_TEMPLATE/backend---bug-report.md
  .github/ISSUE_TEMPLATE/feature-request---problem.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/frontend---bug-report.md
Labels: documentation, enhancement

#42 Frontend HTTP helper function
  Tabby/README.md
  Tabby/app.json
  Tabby/app/library/[category]/[book].tsx
  Tabby/assets/icons/app/icon.png
  Tabby/assets/icons/app/logo.png
  Tabby/example.env
  Tabby/package-lock.json
  Tabby/package.json
  Tabby/types/api_request.ts
  Tabby/types/error.ts
  Tabby/types/error_handle.ts
Labels: documentation, enhancement, frontend, Urgent

#41 Google Books Implementation
  server/tabby_server/__main__.py
  server/tabby_server/services/flower_of_algernon_test_output
  server/tabby_server/services/gcloud_api_generation.py
  server/tabby_server/services/library.py
  server/tabby_server/services/resource_format.py
  server/tabby_server/test_routes.py
  server/tests/flower_of_algernon_test_40_output.json
  server/tests/test_api.py
  server/tests/test_services.py
Labels: documentation, enhancement, backend

#57 Updated Google Books API
  server/tabby_server/__main__.py
  server/tabby_server/services/library.py
  server/tabby_server/services/resource_format.py
  server/tests/test_api.py
  server/tests/test_services.py
Labels: documentation, enhancement, backend

#62 Upgrade expo sdk to 52
  Tabby/app.json
  Tabby/app/__tests__/Favorite_Test.js
  Tabby/app/__tests__/SearchBar_Test.js
  Tabby/components/camera/CameraModel.tsx
  Tabby/package-lock.json
  Tabby/package.json
Labels: frontend

#67 Recommendations
  server/README.md
  server/samples/books_search/1-in.txt
  server/samples/books_search/1-out.json
  server/samples/books_search/2-in.txt
  server/samples/books_search/2-out.json
  server/samples/books_search/bad1-in.txt
  server/samples/books_search/bad1-out.txt
  server/samples/books_search/noresults-in.txt
  server/tabby_server/api/books.py
  server/tabby_server/services/google_books.py
  server/tabby_server/services/tags.py
  server/tests/test_api.py
  server/tests/test_google_books.py
  server/tests/test_tags.py
Labels: documentation, enhancement, backend

#74 Koyeb Deployment Push
  .devcontainer/devcontainer.json
  .github/assets/koyeb_build.png
  .github/assets/koyeb_instance.png
  .github/assets/koyeb_instances.png
  .github/assets/koyeb_overview.png
  .github/assets/koyeb_pause.png
  .github/assets/koyeb_regions.png
  .github/assets/koyeb_resume.png
  .github/assets/koyeb_service_type.png
  .github/assets/koyeb_settings.png
  .github/assets/koyeb_source.png
  server/.dockerignore
  server/Dockerfile
  server/Procfile
  server/README.md
  server/poetry.lock
  server/pyproject.toml
  server/requirements.txt
  server/tabby_server/__init__.py
  server/tabby_server/__main__.py
  server/tests/test_api.py
Labels: documentation, enhancement, frontend, backend, Urgent

#47 Adding database
  Tabby/app.json
  Tabby/app/__tests__/Render_Categories_Test.js
  Tabby/app/__tests__/Render_Favorites_Test.js
  Tabby/app/__tests__/SearchBar_Test.js
  Tabby/app/__tests__/Setting_Test.js
  Tabby/app/_layout.tsx
  Tabby/app/favorites.tsx
  Tabby/app/library/[category]/[book].tsx
  Tabby/app/library/[category]/index.tsx
  Tabby/app/library/index.tsx
  Tabby/app/recommendations/[book].tsx
  Tabby/app/recommendations/index.tsx
  Tabby/app/setting/index.tsx
  Tabby/assets/book/default-book-cover.jpg
  Tabby/assets/book/edit-pen-icon.svg
  Tabby/assets/menu-icons/add-square-icon.svg
  Tabby/assets/menu-icons/bars-icon.svg
  Tabby/assets/menu-icons/cancel-icon.svg
  Tabby/assets/menu-icons/category-select-icon.svg
  Tabby/assets/menu-icons/delete-icon.svg
  Tabby/assets/menu-icons/plus-icon.svg
  Tabby/assets/menu-icons/rename-icon.svg
  Tabby/components/AddBooksOrMoveBooksToCategoryModal.tsx
  Tabby/components/BookCard.tsx
  Tabby/components/BookPreview.tsx
  Tabby/components/DeleteBooksModal.tsx
  Tabby/components/FooterNavBar.tsx
  Tabby/components/LoadingSpinner.tsx
  Tabby/components/book/AddOrMoveSingleBookModal.tsx
  Tabby/components/book/BookCard.tsx
  Tabby/components/book/DeleteBookModal.tsx
  Tabby/components/book/DropDownMenu.tsx
  Tabby/components/book/DropDownModal.tsx
  Tabby/components/book/Reviews.tsx
  Tabby/components/book/ScrollableHorizontalList.tsx
  Tabby/components/book/StarsRating.tsx
  Tabby/components/book/UpdateBookNotesModal.tsx
  Tabby/components/camera/CameraModel.tsx
  Tabby/components/categories/DeleteConfirmationModal.tsx
  Tabby/components/categories/RenameModal.tsx
  Tabby/components/categories/SelectedMenu.tsx
  Tabby/components/navbar/camera.tsx
  Tabby/components/navbar/notSelectedExplore.tsx
  Tabby/components/navbar/notSelectedFavorite.tsx
  Tabby/components/navbar/notSelectedLibrary.tsx
  Tabby/components/navbar/selectedExplore.tsx
  Tabby/components/navbar/selectedFavorite.tsx
  Tabby/components/navbar/selectedLibrary.tsx
  Tabby/components/navbar/settings.tsx
  Tabby/components/settings/EyeIcon.tsx
  Tabby/components/settings/ShieldIcon.tsx
  Tabby/database/databaseOperations.ts
  Tabby/database/migration.ts
  Tabby/package-lock.json
  Tabby/package.json
  Tabby/types/book.ts
  Tabby/types/review.ts
Labels: documentation, enhancement, frontend, Urgent
