Repository UNLV-CS472-672/2024-F-GROUP1-Tabby, pull requests merged in 2024-12, with the labels that each got.

#80 Add Logging
  server/requirements.txt
  server/tabby_server/__main__.py
  server/tabby_server/api/books.py
Labels: documentation, enhancement, backend

#92 Implement front end for /scan_cover
  Tabby/app/__tests__/Camera_Test.js
  Tabby/app/__tests__/Favorite_Test.js
  Tabby/app/__tests__/SearchBar_Test.js
  Tabby/app/favorites.tsx
  Tabby/app/library/[category]/index.tsx
  Tabby/components/FooterNavBar.tsx
  Tabby/components/camera/CameraModel.tsx
  Tabby/example.env
  Tabby/package-lock.json
  Tabby/package.json
Labels: documentation, enhancement, frontend, Urgent

#99 Implement scan shelf
  Tabby/app/__tests__/Camera_Test.js
  Tabby/app/__tests__/Render_Categories_Test.js
  Tabby/components/FooterNavBar.tsx
  Tabby/components/camera/CameraModel.tsx
Labels: enhancement, frontend

#100 Update README.md
  README.md
Labels: documentation, backend
